const allKeys = [
  [
    { defaultText: '`' },
    { defaultText: '1' },
    { defaultText: '2' },
    { defaultText: '3' },
    { defaultText: '4' },
    { defaultText: '5' },
    { defaultText: '6' },
    { defaultText: '7' },
    { defaultText: '8' },
    { defaultText: '9' },
    { defaultText: '0' },
    { defaultText: '-' },
    { defaultText: '=' },
    { defaultText: 'del', isWide: true },
  ],
  [
    { defaultText: 'tab', isWide: true },
    { defaultText: 'Q' },
    { defaultText: 'W' },
    { defaultText: 'E' },
    { defaultText: 'R' },
    { defaultText: 'T' },
    { defaultText: 'Y' },
    { defaultText: 'U' },
    { defaultText: 'I' },
    { defaultText: 'O' },
    { defaultText: 'P' },
    { defaultText: '[' },
    { defaultText: ']' },
    { defaultText: '\\' },
  ],
  [
    { defaultText: 'caps lock', isWide: true },
    { defaultText: 'A' },
    { defaultText: 'S' },
    { defaultText: 'D' },
    { defaultText: 'F' },
    { defaultText: 'G' },
    { defaultText: 'H' },
    { defaultText: 'J' },
    { defaultText: 'K' },
    { defaultText: 'L' },
    { defaultText: ';' },
    { defaultText: '\'' },
    { defaultText: 'return', isWide: true },
  ],
  [
    { defaultText: 'shift', isWide: true },
    { defaultText: 'Z' },
    { defaultText: 'X' },
    { defaultText: 'C' },
    { defaultText: 'V' },
    { defaultText: 'B' },
    { defaultText: 'N' },
    { defaultText: 'M' },
    { defaultText: ',' },
    { defaultText: '.' },
    { defaultText: '/' },
    { defaultText: '▲' },
    { defaultText: 'shift' },
  ],
  [
    { defaultText: 'fn' },
    { defaultText: 'control' },
    { defaultText: 'option' },
    { defaultText: 'cmd' },
    { defaultText: ' ', isWide: true },
    { defaultText: 'cmd' },
    { defaultText: 'option' },
    { defaultText: '◄' },
    { defaultText: '▼' },
    { defaultText: '►' },
  ],
];

console.log(allKeys);
